import { AIProvider, GenerationRequest, GenerationResult } from './types'
import axios from 'axios'

const STABILITY_API_URL = 'https://api.stability.ai/v1'
const STABILITY_API_KEY = process.env.STABILITY_API_KEY

export class StabilityProvider implements AIProvider {
  name = 'stability'

  async isHealthy(): Promise<boolean> {
    try {
      if (!STABILITY_API_KEY) {
        console.warn('Stability API key not configured')
        return false
      }

      const response = await axios.get(
        `${STABILITY_API_URL}/user/account`,
        {
          timeout: 5000,
          headers: {
            'Authorization': `Bearer ${STABILITY_API_KEY}`,
            'Accept': 'application/json',
          },
          validateStatus: () => true,
        }
      )

      return response.status < 500
    } catch (error) {
      console.error('Stability health check failed:', error)
      return false
    }
  }

  async generate(request: GenerationRequest): Promise<GenerationResult> {
    if (!STABILITY_API_KEY) {
      throw new Error('Stability API key not configured')
    }

    try {
      const width = request.settings.width || 512
      const height = request.settings.height || 512
      const steps = request.settings.steps || 50
      const guidanceScale = request.settings.guidance_scale || 7.5
      const seed = request.settings.seed

      const payload = {
        text_prompts: [
          {
            text: request.prompt,
            weight: 1
          }
        ],
        height: height,
        width: width,
        steps: steps,
        guidance_scale: guidanceScale,
        samples: request.settings.num_variations || 1,
      }

      if (request.negativePrompt) {
        payload.text_prompts.push({
          text: request.negativePrompt,
          weight: -1
        })
      }

      if (seed !== undefined) {
        (payload as any).seed = seed
      }

      const response = await axios.post(
        `${STABILITY_API_URL}/generation/stable-diffusion-3/text-to-image`,
        payload,
        {
          timeout: parseInt(process.env.GENERATION_PROVIDER_TIMEOUT_SECONDS || '60') * 1000,
          headers: {
            'Authorization': `Bearer ${STABILITY_API_KEY}`,
            'Content-Type': 'application/json',
          }
        }
      )

      if (response.status !== 200) {
        throw new Error(`Stability API error: ${response.status} ${response.statusText}`)
      }

      // Extract image URLs from response
      const imageUrls: string[] = response.data.artifacts?.map((artifact: any) => artifact.base64) || []

      if (imageUrls.length === 0) {
        throw new Error('No images generated by Stability API')
      }

      return {
        imageUrls,
        metadata: {
          model: 'stable-diffusion-3',
          provider: this.name,
          seed: seed,
        }
      }
    } catch (error) {
      if (axios.isAxiosError(error)) {
        throw new Error(`Stability generation failed: ${error.message}`)
      }
      throw error
    }
  }
}

export const stabilityProvider = new StabilityProvider()
